version: "3"

services:
  web:
    container_name: web
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    entrypoint: [ "/app/entrypoint.sh", "web" ]

  db:
    container_name: db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    env_file:
      - .env
    restart: unless-stopped

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data/cache
    depends_on:
      - web
    restart: unless-stopped

volumes:
  mongo:
  redis: